<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib\Tests\Controllers;

use Core\TestCase\TestParam;
use ServiceLayerUOCLib\Controllers\BusinessPartnersController;
use ServiceLayerUOCLib\Exceptions;
use ServiceLayerUOCLib\Models;

class BusinessPartnersControllerTest extends BaseTestController
{
    /**
     * @var BusinessPartnersController BusinessPartnersController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getBusinessPartnersController();
    }

    public function testListarTodos()
    {
        // Perform API call
        try {
            self::$controller->listarTodos();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testVerBusinessPartner()
    {
        // Parameters for the API call
        $select = 'CardCode,CardName,CardType';

        // Perform API call
        try {
            self::$controller->verBusinessPartner($select);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testActualizar()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"CardName\": \"Updated customer name\"\r\n}",
            Models\ActualizarRequest::class
        );

        // Perform API call
        try {
            self::$controller->actualizar($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
