<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib\Http;

use Core\Types\Sdk\CoreRequest;

/**
 * Represents a single Http Request
 */
class HttpRequest extends CoreRequest
{
}
