<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib\Controllers;

use Core\Request\Parameters\BodyParam;
use CoreInterfaces\Core\Request\RequestMethod;
use ServiceLayerUOCLib\Exceptions\ApiException;
use ServiceLayerUOCLib\Models\LoginUOCRequest;
use ServiceLayerUOCLib\Server;

class AuthenticationController extends BaseController
{
    /**
     * UOC Auth Params:
     * {
     * "CompanyDB": "UOC_TEST30V2",
     * "UserName": "integrador",
     * "Password": "B1AdminUOC"
     * }
     *
     * Retorna 2 cookies (RouteID; B1SESSION) que deben ser almacenadas y añadidas en el {header} de todas
     * las consultas siguientes.
     *
     * @param LoginUOCRequest $body
     *
     * @return LoginUOCRequest Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function loginUOC(LoginUOCRequest $body): LoginUOCRequest
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/Login')
            ->server(Server::SERVER_3)
            ->parameters(BodyParam::init($body));

        $_resHandler = $this->responseHandler()->type(LoginUOCRequest::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function logoutUOC(): void
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/Logout')->server(Server::SERVER_3);

        $this->execute($_reqBuilder);
    }
}
