<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib\Models;

use stdClass;

class ActualizarRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $cardName;

    /**
     * @param string $cardName
     */
    public function __construct(string $cardName)
    {
        $this->cardName = $cardName;
    }

    /**
     * Returns Card Name.
     */
    public function getCardName(): string
    {
        return $this->cardName;
    }

    /**
     * Sets Card Name.
     *
     * @required
     * @maps CardName
     */
    public function setCardName(string $cardName): void
    {
        $this->cardName = $cardName;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['CardName'] = $this->cardName;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
