<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib\Models;

use stdClass;

class CrearNuevoRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $cardCode;

    /**
     * @var string
     */
    private $cardName;

    /**
     * @var string
     */
    private $cardType;

    /**
     * @var string
     */
    private $federalTaxID;

    /**
     * @param string $cardCode
     * @param string $cardName
     * @param string $cardType
     * @param string $federalTaxID
     */
    public function __construct(string $cardCode, string $cardName, string $cardType, string $federalTaxID)
    {
        $this->cardCode = $cardCode;
        $this->cardName = $cardName;
        $this->cardType = $cardType;
        $this->federalTaxID = $federalTaxID;
    }

    /**
     * Returns Card Code.
     */
    public function getCardCode(): string
    {
        return $this->cardCode;
    }

    /**
     * Sets Card Code.
     *
     * @required
     * @maps CardCode
     */
    public function setCardCode(string $cardCode): void
    {
        $this->cardCode = $cardCode;
    }

    /**
     * Returns Card Name.
     */
    public function getCardName(): string
    {
        return $this->cardName;
    }

    /**
     * Sets Card Name.
     *
     * @required
     * @maps CardName
     */
    public function setCardName(string $cardName): void
    {
        $this->cardName = $cardName;
    }

    /**
     * Returns Card Type.
     */
    public function getCardType(): string
    {
        return $this->cardType;
    }

    /**
     * Sets Card Type.
     *
     * @required
     * @maps CardType
     */
    public function setCardType(string $cardType): void
    {
        $this->cardType = $cardType;
    }

    /**
     * Returns Federal Tax ID.
     */
    public function getFederalTaxID(): string
    {
        return $this->federalTaxID;
    }

    /**
     * Sets Federal Tax ID.
     *
     * @required
     * @maps FederalTaxID
     */
    public function setFederalTaxID(string $federalTaxID): void
    {
        $this->federalTaxID = $federalTaxID;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['CardCode']     = $this->cardCode;
        $json['CardName']     = $this->cardName;
        $json['CardType']     = $this->cardType;
        $json['FederalTaxID'] = $this->federalTaxID;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
