<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib\Models;

use stdClass;

class CrearNuevoRequest1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $cardCode;

    /**
     * @var DocumentLine[]
     */
    private $documentLines;

    /**
     * @param string $cardCode
     * @param DocumentLine[] $documentLines
     */
    public function __construct(string $cardCode, array $documentLines)
    {
        $this->cardCode = $cardCode;
        $this->documentLines = $documentLines;
    }

    /**
     * Returns Card Code.
     */
    public function getCardCode(): string
    {
        return $this->cardCode;
    }

    /**
     * Sets Card Code.
     *
     * @required
     * @maps CardCode
     */
    public function setCardCode(string $cardCode): void
    {
        $this->cardCode = $cardCode;
    }

    /**
     * Returns Document Lines.
     *
     * @return DocumentLine[]
     */
    public function getDocumentLines(): array
    {
        return $this->documentLines;
    }

    /**
     * Sets Document Lines.
     *
     * @required
     * @maps DocumentLines
     *
     * @param DocumentLine[] $documentLines
     */
    public function setDocumentLines(array $documentLines): void
    {
        $this->documentLines = $documentLines;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['CardCode']      = $this->cardCode;
        $json['DocumentLines'] = $this->documentLines;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
