<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib\Models;

use stdClass;

class DocumentLine implements \JsonSerializable
{
    /**
     * @var string
     */
    private $itemCode;

    /**
     * @var string
     */
    private $quantity;

    /**
     * @var string
     */
    private $taxCode;

    /**
     * @var string
     */
    private $unitPrice;

    /**
     * @param string $itemCode
     * @param string $quantity
     * @param string $taxCode
     * @param string $unitPrice
     */
    public function __construct(string $itemCode, string $quantity, string $taxCode, string $unitPrice)
    {
        $this->itemCode = $itemCode;
        $this->quantity = $quantity;
        $this->taxCode = $taxCode;
        $this->unitPrice = $unitPrice;
    }

    /**
     * Returns Item Code.
     */
    public function getItemCode(): string
    {
        return $this->itemCode;
    }

    /**
     * Sets Item Code.
     *
     * @required
     * @maps ItemCode
     */
    public function setItemCode(string $itemCode): void
    {
        $this->itemCode = $itemCode;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): string
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * @required
     * @maps Quantity
     */
    public function setQuantity(string $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Tax Code.
     */
    public function getTaxCode(): string
    {
        return $this->taxCode;
    }

    /**
     * Sets Tax Code.
     *
     * @required
     * @maps TaxCode
     */
    public function setTaxCode(string $taxCode): void
    {
        $this->taxCode = $taxCode;
    }

    /**
     * Returns Unit Price.
     */
    public function getUnitPrice(): string
    {
        return $this->unitPrice;
    }

    /**
     * Sets Unit Price.
     *
     * @required
     * @maps UnitPrice
     */
    public function setUnitPrice(string $unitPrice): void
    {
        $this->unitPrice = $unitPrice;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['ItemCode']  = $this->itemCode;
        $json['Quantity']  = $this->quantity;
        $json['TaxCode']   = $this->taxCode;
        $json['UnitPrice'] = $this->unitPrice;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
