<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use ServiceLayerUOCLib\Controllers\AuthenticationController;
use ServiceLayerUOCLib\Controllers\BusinessPartnersController;
use ServiceLayerUOCLib\Controllers\QuotationsController;
use ServiceLayerUOCLib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class ServiceLayerUOCClient implements ConfigurationInterface
{
    private $authentication;

    private $businessPartners;

    private $quotations;

    private $config;

    private $client;

    /**
     * @see ServiceLayerUOCClientBuilder::init()
     * @see ServiceLayerUOCClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->client = ClientBuilder::init(new HttpClient(Configuration::init($this)))
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('APIMATIC 3.0')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::UOC)
            ->build();
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return ServiceLayerUOCClientBuilder ServiceLayerUOCClientBuilder instance
     */
    public function toBuilder(): ServiceLayerUOCClientBuilder
    {
        return ServiceLayerUOCClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null);
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see ServiceLayerUOCClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see ServiceLayerUOCClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::UOC): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Authentication Controller
     */
    public function getAuthenticationController(): AuthenticationController
    {
        if ($this->authentication == null) {
            $this->authentication = new AuthenticationController($this->client);
        }
        return $this->authentication;
    }

    /**
     * Returns Business Partners Controller
     */
    public function getBusinessPartnersController(): BusinessPartnersController
    {
        if ($this->businessPartners == null) {
            $this->businessPartners = new BusinessPartnersController($this->client);
        }
        return $this->businessPartners;
    }

    /**
     * Returns Quotations Controller
     */
    public function getQuotationsController(): QuotationsController
    {
        if ($this->quotations == null) {
            $this->quotations = new QuotationsController($this->client);
        }
        return $this->quotations;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::PRODUCTION => [
            Server::UOC => 'https://190.167.220.163:50000/b1s/v1',
            Server::SERVER_3 => 'https://190.167.220.163:50000/b1s/v1'
        ]
    ];
}
