<?php

declare(strict_types=1);

/*
 * ServiceLayerUOCLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ServiceLayerUOCLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const UOC = 'UOC';

    public const SERVER_3 = 'Server 3';
}
